--- EDITORIALBOARD
DROP ROLE EDITORIALBOARD;
DROP LOGIN eb1;
DROP USER eb1;

CREATE ROLE EDITORIALBOARD;
GRANT SELECT, UPDATE ON ARTICLE TO EDITORIALBOARD;
GRANT SELECT ON RESEARCH TO EDITORIALBOARD;
GRANT SELECT ON OVERVIEW TO EDITORIALBOARD;
GRANT SELECT ON REVIEW_BOOK TO EDITORIALBOARD;
GRANT SELECT, INSERT, UPDATE ON CRITERIA TO EDITORIALBOARD;
GRANT SELECT, INSERT, UPDATE ON ASSIGN TO EDITORIALBOARD;

GRANT EXECUTE ON OBJECT::updateAssign TO EDITORIALBOARD; 
GRANT EXECUTE ON OBJECT::updateStatusArticle TO EDITORIALBOARD;  
GRANT EXECUTE ON OBJECT::UpdateResult TO EDITORIALBOARD;  
GRANT EXECUTE ON OBJECT::ViewArticleByStatus TO EDITORIALBOARD;  
GRANT EXECUTE ON OBJECT::ViewArticleByTypeByYear TO EDITORIALBOARD;  
GRANT EXECUTE ON OBJECT::ViewArticleByTypeByAuthor TO EDITORIALBOARD;  
GRANT EXECUTE ON OBJECT::CountArticleByType TO EDITORIALBOARD;  

REVOKE SELECT, UPDATE ON ARTICLE TO EDITORIALBOARD;
REVOKE SELECT ON RESEARCH TO EDITORIALBOARD;
REVOKE SELECT ON OVERVIEW TO EDITORIALBOARD;
REVOKE SELECT ON REVIEW_BOOK TO EDITORIALBOARD;
REVOKE SELECT, INSERT, UPDATE ON CRITERIA TO EDITORIALBOARD;
REVOKE SELECT, INSERT, UPDATE ON ASSIGN TO EDITORIALBOARD;

REVOKE EXECUTE ON OBJECT::updateAssign TO EDITORIALBOARD; 
REVOKE EXECUTE ON OBJECT::updateStatusArticle TO EDITORIALBOARD;  
REVOKE EXECUTE ON OBJECT::UpdateResult TO EDITORIALBOARD;  
REVOKE EXECUTE ON OBJECT::ViewArticleByStatus TO EDITORIALBOARD;  
REVOKE EXECUTE ON OBJECT::ViewArticleByTypeByYear TO EDITORIALBOARD;  
REVOKE EXECUTE ON OBJECT::ViewArticleByTypeByAuthor TO EDITORIALBOARD;  
REVOKE EXECUTE ON OBJECT::CountArticleByType TO EDITORIALBOARD;  

CREATE LOGIN eb1 WITH PASSWORD = '123456';
CREATE USER eb1 FOR LOGIN eb1;
EXEC sp_addrolemember 'EDITORIALBOARD', 'eb1'; 

--- REVIEWER
DROP ROLE REVIEWER;
DROP LOGIN rv1;
DROP USER rv1;
CREATE ROLE REVIEWER;
GRANT SELECT ON ARTICLE TO REVIEWER;
GRANT SELECT ON RESEARCH TO REVIEWER;
GRANT SELECT ON OVERVIEW TO REVIEWER;
GRANT SELECT ON REVIEW_BOOK TO REVIEWER;
GRANT SELECT ON ASSIGN TO REVIEWER;
GRANT SELECT, UPDATE ON EVALUATE TO REVIEWER;
GRANT SELECT, UPDATE ON SCIENTIST TO REVIEWER;
GRANT SELECT, UPDATE ON FIELD TO REVIEWER;

GRANT EXECUTE ON OBJECT::UpdateInformation TO REVIEWER; 
GRANT EXECUTE ON OBJECT::UpdateCriteriaContent TO REVIEWER;  
GRANT EXECUTE ON OBJECT::ViewArticleReviewing TO REVIEWER;  
GRANT EXECUTE ON OBJECT::ViewArticleReviewedIn3Y TO REVIEWER;  
GRANT EXECUTE ON OBJECT::ViewArticleOfAuthorReviewing TO REVIEWER;  
GRANT EXECUTE ON OBJECT::ViewArticleOfAuthorReviewingIn3Y TO REVIEWER;  
GRANT EXECUTE ON OBJECT::getXListTopAuthorReviewed TO REVIEWER;  
GRANT EXECUTE ON OBJECT::ViewResultArticleReviewed TO REVIEWER;  
GRANT EXECUTE ON OBJECT::get3YearsHaveTopArticleReviewed TO REVIEWER;  
GRANT EXECUTE ON OBJECT::ViewArticleReviewedBestResult TO REVIEWER;  
GRANT EXECUTE ON OBJECT::ViewArticleReviewedWorstResult TO REVIEWER;  
GRANT EXECUTE ON OBJECT::getNumOfArticleReviewedin5Years TO REVIEWER;  
GRANT EXECUTE ON OBJECT::ViewNArticleReviewedWithResult TO REVIEWER;  


REVOKE SELECT ON ARTICLE TO REVIEWER;
REVOKE SELECT ON RESEARCH TO REVIEWER;
REVOKE SELECT ON OVERVIEW TO REVIEWER;
REVOKE SELECT ON REVIEW_BOOK TO REVIEWER;
REVOKE SELECT ON ASSIGN TO REVIEWER;
REVOKE SELECT, UPDATE ON EVALUATE TO REVIEWER;
REVOKE SELECT, UPDATE ON SCIENTIST TO REVIEWER;
REVOKE SELECT, UPDATE ON FIELD TO REVIEWER;

REVOKE EXECUTE ON OBJECT::UpdateInformation TO REVIEWER; 
REVOKE EXECUTE ON OBJECT::UpdateCriteriaContent TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::ViewArticleReviewing TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::ViewArticleReviewedIn3Y TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::ViewArticleOfAuthorReviewing TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::ViewArticleOfAuthorReviewingIn3Y TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::getXListTopAuthorReviewed TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::ViewResultArticleReviewed TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::get3YearsHaveTopArticleReviewed TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::ViewArticleReviewedBestResult TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::ViewArticleReviewedWorstResult TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::getNumOfArticleReviewedin5Years TO REVIEWER;  
REVOKE EXECUTE ON OBJECT::ViewNArticleReviewedWithResult TO REVIEWER;  

CREATE LOGIN rv1 WITH PASSWORD = '123456';
CREATE USER rv1 FOR LOGIN rv1;
EXEC sp_addrolemember 'REVIEWER', 'rv1';

--- AUTHOR CONTACT
DROP ROLE AUTHORCON;
DROP LOGIN auc1;
DROP USER auc1;
CREATE ROLE AUTHORCON;
GRANT SELECT, UPDATE ON SCIENTIST TO AUTHORCON;
GRANT SELECT, INSERT, UPDATE ON ARTICLE TO AUTHORCON;
GRANT SELECT, INSERT, UPDATE ON RESEARCH TO AUTHORCON;
GRANT SELECT, INSERT, UPDATE ON OVERVIEW TO AUTHORCON;
GRANT SELECT, INSERT, UPDATE ON REVIEW_BOOK TO AUTHORCON;
GRANT SELECT, INSERT, UPDATE ON WRITE TO AUTHORCON;
GRANT SELECT ON EVALUATE TO AUTHORCON;
GRANT SELECT, UPDATE ON FIELD TO AUTHORCON;

GRANT EXECUTE ON OBJECT::updateProfile TO AUTHORCON; 
GRANT EXECUTE ON OBJECT::updateArticle TO AUTHORCON;  
GRANT EXECUTE ON OBJECT::getAuthorInfoOfArticle TO AUTHORCON;  
GRANT EXECUTE ON OBJECT::getStatusofArticle TO AUTHORCON;  
GRANT EXECUTE ON OBJECT::getResultofArticle TO AUTHORCON;  
GRANT EXECUTE ON OBJECT::getListArticle TO AUTHORCON;  
GRANT EXECUTE ON OBJECT::getListArticleAccepted TO AUTHORCON;  
GRANT EXECUTE ON OBJECT::getListArticlePublishing TO AUTHORCON;  
GRANT EXECUTE ON OBJECT::getListArticleRejected TO AUTHORCON;  
GRANT EXECUTE ON OBJECT::getNumArticleIn5Years TO AUTHORCON;  
GRANT EXECUTE ON OBJECT::getListResearchArticleAcceptedIn5Years TO AUTHORCON;  
GRANT EXECUTE ON OBJECT::getListOverviewArticleAcceptedIn5Years TO AUTHORCON; 
GRANT EXECUTE ON OBJECT::getListArticleInNYears TO AUTHORCON; 

REVOKE SELECT, UPDATE ON SCIENTIST TO AUTHORCON;
REVOKE SELECT, INSERT, UPDATE ON ARTICLE TO AUTHORCON;
REVOKE SELECT, INSERT, UPDATE ON RESEARCH TO AUTHORCON;
REVOKE SELECT, INSERT, UPDATE ON OVERVIEW TO AUTHORCON;
REVOKE SELECT, INSERT, UPDATE ON REVIEW_BOOK TO AUTHORCON;
REVOKE SELECT, INSERT, UPDATE ON WRITE TO AUTHORCON;
REVOKE SELECT ON EVALUATE TO AUTHORCON;
REVOKE SELECT, UPDATE ON FIELD TO AUTHORCON;

REVOKE EXECUTE ON OBJECT::updateProfile TO AUTHORCON; 
REVOKE EXECUTE ON OBJECT::updateArticle TO AUTHORCON;  
REVOKE EXECUTE ON OBJECT::getAuthorInfoOfArticle TO AUTHORCON;  
REVOKE EXECUTE ON OBJECT::getStatusofArticle TO AUTHORCON;  
REVOKE EXECUTE ON OBJECT::getResultofArticle TO AUTHORCON;  
REVOKE EXECUTE ON OBJECT::getListArticle TO AUTHORCON;  
REVOKE EXECUTE ON OBJECT::getListArticleAccepted TO AUTHORCON;  
REVOKE EXECUTE ON OBJECT::getListArticlePublishing TO AUTHORCON;  
REVOKE EXECUTE ON OBJECT::getListArticleRejected TO AUTHORCON;  
REVOKE EXECUTE ON OBJECT::getNumArticleIn5Years TO AUTHORCON;  
REVOKE EXECUTE ON OBJECT::getListResearchArticleAcceptedIn5Years TO AUTHORCON;  
REVOKE EXECUTE ON OBJECT::getListArticleInNYears TO AUTHORCON; 

CREATE LOGIN auc1 WITH PASSWORD = '123456';
CREATE USER auc1 FOR LOGIN auc1;
EXEC sp_addrolemember 'AUTHORCON', 'auc1';




